filebeat.inputs:
  - type: filestream
    id: my-node-app-id
    enabled: true
    paths:
      - /app/app.log
    parsers:
      - ndjson:
          target: ""
          add_error_key: true
          ignore_decoding_error: true

output.elasticsearch:
  hosts: ["${ELASTIC_HOST}"]
  username: "${ELASTIC_UNAME}"
  password: "${ELASTIC_PASSWD}"
  index: "exp-app-v2"

setup.template.enabled: false
setup.ilm.enabled: false
setup.template.name: "node-logs"
setup.template.pattern: "node-logs-*"